### ISSUE TITLE
mac构建机执行流水线失败-日志提示插件授权失败

### ISSUE THREAD

**Issue by mikeeastin** [TencentBlueKing/bk-ci#6872]
mac 构建机执行 插件  失败
[30 五月 2022;22:11:37.318][pool-6-thread-1] INFO  c.t.d.w.c.a.AbstractBuildResourceApi:requestForResponse:95 - Request(Request{method=GET, url=http://devops-dev.sssqqqgame.com/ms/store/api/build/store/sensitiveConf/types/ATOM/codes/qqjcheckout, tags={}}) with code 200
[30 五月 2022;22:11:37.319][pool-6-thread-1] INFO  c.t.d.w.c.task.market.MarketAtomTask:execute:256 - atomCode is:qqjcheckout ,atomSensitiveConfResult is:Result(status=0, message=null, data=[])
[30 五月 2022;22:11:37.319][pool-6-thread-1] INFO  c.t.d.w.c.task.market.MarketAtomTask:writeSdkEnv:528 - sdkEnv is:SdkEnv(buildType=AGENT, projectId=200001000, agentId=ygmlvomw, secretKey=uQxki6jJo5zYYqEQJjqFIFrojBydP1y, gateway=http://devops-dev.sssqqqgame.com, buildId=b-28b25741f87a40dbbf5d134de910f043, vmSeqId=1)
[30 五月 2022;22:11:37.371][pool-6-thread-1] INFO  c.t.d.w.c.a.AbstractBuildResourceApi:requestForResponse:95 - Request(Request{method=GET, url=http://devops-dev.sssqqqgame.com/ms/artifactory/api/build/artifactories/file/download?filePath=bk-atom%2F200001000%2Fqqjcheckout%2F1.0.0%2Fcheckout.jar, tags={}}) with code 200
[30 五月 2022;22:11:37.372][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='##[debug]save file >>>> /private/var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/qqjcheckout_e-aa5a4519ced045078672863eddd8ba19_data816655823423700988/checkout.jar', timestamp=1653919897372), logType=DEBUG, executeCount=1)
[30 五月 2022;22:11:37.372][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='download2 checkout.jar N/A', timestamp=1653919897372), logType=LOG, executeCount=1)
[30 五月 2022;22:11:37.640][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='ok save file === /var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/qqjcheckout_e-aa5a4519ced045078672863eddd8ba19_data816655823423700988/checkout.jar', timestamp=1653919897640), logType=LOG, executeCount=1)
[30 五月 2022;22:11:37.714][pool-6-thread-1] INFO  c.t.d.w.c.a.AbstractBuildResourceApi:requestForResponse:95 - Request(Request{method=GET, url=http://devops-dev.sssqqqgame.com/store/api/build/market/atom/dev/language/env/var/languages/java/types/THIRD/oss/MAC_OS, tags={}}) with code 200
[30 五月 2022;22:11:37.714][pool-6-thread-1] INFO  c.t.d.w.c.task.market.MarketAtomTask:execute:296 - atomCode is:qqjcheckout ,atomDevLanguageEnvVarsResult is:Result(status=0, message=null, data=[])
[30 五月 2022;22:11:37.715][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='', timestamp=1653919897715), logType=LOG, executeCount=1)
[30 五月 2022;22:11:37.715][pool-6-thread-1] INFO  c.t.d.w.c.s.i.JavaAtomTargetHandleServiceImpl:handleAtomTarget:50 - handleAtomTarget|target:$bk_java_path -Dfile.encoding=utf8 -jar checkout.jar,osType:MAC_OS,buildHostType:THIRD
[30 五月 2022;22:11:37.715][pool-6-thread-1] INFO  c.t.d.w.c.s.i.JavaAtomTargetHandleServiceImpl:handleAtomTarget:60 - handleAtomTarget convertTarget:$bk_java_path -Dfile.encoding=utf8 -DpostEntryParam=True -jar checkout.jar
[30 五月 2022;22:11:37.716][pool-6-thread-1] WARN  c.t.d.w.c.utils.CommandLineUtils:execute:144 - Fail to execute the command(chmod +x /var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/devops_script8693568181150784798.sh)
java.io.IOException: Cannot run program "chmod" (in directory "/var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/qqjcheckout_e-aa5a4519ced045078672863eddd8ba19_data816655823423700988"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.executeInternal(CommandLineExecutor.kt:79)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.execute(CommandLineExecutor.kt:56)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute(CommandLineUtils.kt:134)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute$default(CommandLineUtils.kt:61)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand(ShellUtil.kt:214)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand$default(ShellUtil.kt:211)
	at com.tencent.devops.worker.common.utils.ShellUtil.getCommandFile(ShellUtil.kt:198)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute(ShellUtil.kt:97)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute$default(ShellUtil.kt:94)
	at com.tencent.devops.worker.common.task.market.MarketAtomTask.execute(MarketAtomTask.kt:358)
	at com.tencent.devops.worker.common.task.ITask.run(ITask.kt:75)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:52)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 21 common frames omitted
[30 五月 2022;22:11:37.716][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='##[error] Fail to execute the command(chmod +x /var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/devops_script8693568181150784798.sh)', timestamp=1653919897716), logType=ERROR, executeCount=1)
[30 五月 2022;22:11:37.717][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-aa5a4519ced045078672863eddd8ba19', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='Fail to run the command chmod +x /var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/devops_script8693568181150784798.sh because of error(Cannot run program "chmod" (in directory "/var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/qqjcheckout_e-aa5a4519ced045078672863eddd8ba19_data816655823423700988"): error=2, No such file or directory)', timestamp=1653919897717), logType=LOG, executeCount=1)
[30 五月 2022;22:11:37.717][pool-6-thread-1] WARN  c.t.d.w.c.task.market.MarketAtomTask:execute:374 - Market atom execution exit with StackTrace:

com.tencent.devops.common.api.exception.TaskExecuteException: Cannot run program "chmod" (in directory "/var/folders/ls/8lblf0tx3ll77j38d4vws1d00000gn/T/qqjcheckout_e-aa5a4519ced045078672863eddd8ba19_data816655823423700988"): error=2, No such file or directory
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand(ShellUtil.kt:226)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand$default(ShellUtil.kt:211)
	at com.tencent.devops.worker.common.utils.ShellUtil.getCommandFile(ShellUtil.kt:198)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute(ShellUtil.kt:97)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute$default(ShellUtil.kt:94)
	at com.tencent.devops.worker.common.task.market.MarketAtomTask.execute(MarketAtomTask.kt:358)
	at com.tencent.devops.worker.common.task.ITask.run(ITask.kt:75)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:52)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[30 五月 2022;22:11:37.717][pool-6-thread-1] INFO  c.t.d.w.c.task.market.MarketAtomTask:output:586 - the atomResult from Market is :
null

**Comment by mikeeastin** [comment]
Runtime.getRuntime().exec("chmod +x ${file.absolutePath}")
改成 ：
Runtime.getRuntime().exec("/bin/chmod +x ${file.absolutePath}")
报错依旧：
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-8dc895f1dabc4b72889223b325863ebc', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='executeUnixCommand :/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh', timestamp=1653984173498), logType=LOG, executeCount=1)
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:65 - 1111:/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:67 - 2222:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh]
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:135 - 3333:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh]
[31 五月 2022;16:02:53.499][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineExecutor:executeInternal:80 - start exec command:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh] dir:/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014 executable:/bin/chmod
[31 五月 2022;16:02:53.499][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineExecutor:executeInternal:83 - mac exec command:
[31 五月 2022;16:02:53.499][pool-6-thread-1] WARN  c.t.d.w.c.utils.CommandLineUtils:execute:146 - Fail to execute the command(/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh)
java.io.IOException: Cannot run program "/bin/chmod" (in directory "/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.executeInternal(CommandLineExecutor.kt:85)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.execute(CommandLineExecutor.kt:58)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute(CommandLineUtils.kt:136)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute$default(CommandLineUtils.kt:61)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand(ShellUtil.kt:216)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand$default(ShellUtil.kt:212)
	at com.tencent.devops.worker.common.utils.ShellUtil.getCommandFile(ShellUtil.kt:199)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute(ShellUtil.kt:97)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute$default(ShellUtil.kt:94)
	at com.tencent.devops.worker.common.task.market.MarketAtomTask.execute(MarketAtomTask.kt:358)
	at com.tencent.devops.worker.common.task.ITask.run(ITask.kt:75)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:52)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)

**Comment by mikeeastin** [comment]
Runtime.getRuntime().exec("chmod +x ${file.absolutePath}")
改成 ：
Runtime.getRuntime().exec("/bin/chmod +x ${file.absolutePath}")
报错依旧：
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.common.logger.LoggerService:addNormalLine:236 - LogMessage(tag='e-8dc895f1dabc4b72889223b325863ebc', subTag='null', jobId='c-55e5e38d22c540c588fb93c36723eeb8', message='executeUnixCommand :/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh', timestamp=1653984173498), logType=LOG, executeCount=1)
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:65 - 1111:/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:67 - 2222:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh]
[31 五月 2022;16:02:53.498][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineUtils:execute:135 - 3333:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh]
[31 五月 2022;16:02:53.499][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineExecutor:executeInternal:80 - start exec command:[/bin/chmod, +x, /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh] dir:/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014 executable:/bin/chmod
[31 五月 2022;16:02:53.499][pool-6-thread-1] INFO  c.t.d.w.c.utils.CommandLineExecutor:executeInternal:83 - mac exec command:
[31 五月 2022;16:02:53.499][pool-6-thread-1] WARN  c.t.d.w.c.utils.CommandLineUtils:execute:146 - Fail to execute the command(/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh)
java.io.IOException: Cannot run program "/bin/chmod" (in directory "/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.executeInternal(CommandLineExecutor.kt:85)
	at com.tencent.devops.worker.common.utils.CommandLineExecutor.execute(CommandLineExecutor.kt:58)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute(CommandLineUtils.kt:136)
	at com.tencent.devops.worker.common.utils.CommandLineUtils.execute$default(CommandLineUtils.kt:61)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand(ShellUtil.kt:216)
	at com.tencent.devops.worker.common.utils.ShellUtil.executeUnixCommand$default(ShellUtil.kt:212)
	at com.tencent.devops.worker.common.utils.ShellUtil.getCommandFile(ShellUtil.kt:199)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute(ShellUtil.kt:97)
	at com.tencent.devops.worker.common.utils.ShellUtil.execute$default(ShellUtil.kt:94)
	at com.tencent.devops.worker.common.task.market.MarketAtomTask.execute(MarketAtomTask.kt:358)
	at com.tencent.devops.worker.common.task.ITask.run(ITask.kt:75)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:52)
	at com.tencent.devops.worker.common.task.TaskDaemon.call(TaskDaemon.kt:44)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)

**Comment by mikeeastin** [comment]
使用的版本为 1.7 release

**Comment by carlyin0801** [comment]
[31 五月 2022;16:02:53.499][pool-6-thread-1] WARN c.t.d.w.c.utils.CommandLineUtils:execute:146 - Fail to execute the command(/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh)
java.io.IOException: Cannot run program "/bin/chmod" (in directory "/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014"): error=2, No such file or directory

看报错是你文件路径有问题，麻烦确认下你文件路径的正确性！

**Comment by mikeeastin** [comment]
/bin/chmod 文件存在 
/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e8dc895f1dabc4b72889223b325863ebc_data8343333086585476014    这个文件也存在

**Comment by mikeeastin** [comment]
直接在 机器上 手工执行 一样的命令，是ok的

**Comment by mikeeastin** [comment]
linux构建机 正常，
mac 构建机才有上述问题

**Comment by carlyin0801** [comment]
麻烦确认下你mac构建机上装的agent是否有执行这个文件的权限排除下

**Comment by mikeeastin** [comment]
使用 root 账户启动的 agent 哈

**Comment by mikeeastin** [comment]
我试了两台  mac ，都是必现的，你们那边无法重现吗？

**Comment by carlyin0801** [comment]
我们这边的mac构建机正常，我们找下负责这块的同事看下具体情况

**Comment by mikeeastin** [comment]
好的，谢谢。我现在不确定是 机器环境配置的问题还是代码的问题。
1、我自己写了一个demo，扔到构建机上执行，是正常执行成功的。
import java.io.IOException;
public class Demo {
 public static void main(String[] args)  throws IOException{
System.out.printf("==="+ Runtime.getRuntime().exec("chmod +x   xxx.txt
 "));
 }
}
2、用了 worker-agent.jar 执行，就 提示   error=2, No such file or directory。 
3、上午的时候怀疑是 chmod 在 mac机器上 找不到环境变量的位置，就 故意改成了 /bin/chmod ，也是一样的报错

**Comment by mikeeastin** [comment]
我猜，您可能对log日志有一点误解。
Fail to execute the command(/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh)
java.io.IOException: Cannot run program "/bin/chmod" (in directory "/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014"): error=2, No such file or directory


这里的 No such file or directory 并不是  说 qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014这个文件不存在哈， 是 /bin/chmod 这个文件不存在的意思。
 因为我试过 修改 executeUnixCommand(command = "ls ") ， 也是会提示  error=2, No such file or directory
【代码在 com.tencent.devops.worker.common.utils.ShellUtil.kt  getCommandFile方法里  】

**Comment by mikeeastin** [comment]
我猜，您可能对log日志有一点误解。
Fail to execute the command(/bin/chmod +x /var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/devops_script3876866410568799078.sh)
java.io.IOException: Cannot run program "/bin/chmod" (in directory "/var/folders/bs/dk1pfy891x9clx24j16fzy_00000gn/T/qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014"): error=2, No such file or directory


这里的 No such file or directory 并不是  说 qqqcheckout_e-8dc895f1dabc4b72889223b325863ebc_data8343333086585476014这个文件不存在哈， 是 /bin/chmod 这个文件不存在的意思。
 因为我试过 修改 executeUnixCommand(command = "ls ") ， 也是会提示  error=2, No such file or directory
【代码在 com.tencent.devops.worker.common.utils.ShellUtil.kt  getCommandFile方法里  】

**Comment by mikeeastin** [comment]
请问 ，，，还有人吗
