### ISSUE TITLE
sh /data/bkee/ci/assembly/assembly.sh start启动报错，着急！！！

### ISSUE THREAD

**Issue by ctd1249746051** [TencentBlueKing/bk-ci#9523]
按照文档编译成功后启动assembly.sh报错如下：

2023.10.08 14:16:09,149|| [        main] INFO  c.u.j.d.DefaultLazyPropertyDetector      35 Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2023.10.08 14:16:10,745|| [        main] ERROR o.s.b.d.LoggingFailureAnalysisReporter   40

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'configServerRetryInterceptor' that could not be found.

Action:

Consider defining a bean named 'configServerRetryInterceptor' in your configuration.

然后按照社区的回答改成（https://github.com/TencentBlueKing/bk-ci/issues/5574）
-Dspring.cloud.config.fail-fast=true

虽然没有报上面的错，但是报了另一个错

2023.10.08 00:36:08,917||| [        main] INFO  c.c.c.ConfigServicePropertySourceLocator 241 Fetching config from server at : http://localhost:8888
2023.10.08 00:36:09,804||| [        main] ERROR o.springframework.boot.SpringApplication 835 Application run failed
java.lang.IllegalStateException: Could not locate PropertySource and the fail fast property is set, failing: None of labels [] found
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locate(ConfigServicePropertySourceLocator.java:148)
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator.locateCollection(ConfigServicePropertySourceLocator.java:160)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$FastClassBySpringCGLIB$$fa44b2a.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:97)
        at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:329)
        at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:209)
        at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:133)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:159)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
        at org.springframework.cloud.config.client.ConfigServicePropertySourceLocator$$EnhancerBySpringCGLIB$$7dc4899f.locateCollection(<generated>)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:618)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:385)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:306)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at com.tencent.devops.common.service.MicroServiceApplication.run(MicroServiceApplication.kt:40)
        at com.tencent.devops.AssemblyApplicationKt.main(AssemblyApplication.kt:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by ctd1249746051** [comment]
分支用的blueking-7.1，公司打算用bkci，但是按照文档一直启动不了，容器版的bkci也只有1.5的

**Comment by stubenhuang** [comment]
1. 尝试关闭config-server : `spring.cloud.config.enabled=false` , 只使用本地的配置文件
2. 容器版的bkci也有7.1 , 到RELEASE页找v2.x.x版本的chart包即可 , 例如: [v2.0.0-beta.35](https://github.com/TencentBlueKing/bk-ci/releases/download/v2.0.0-beta.35/bk-ci-charts.tgz) , 使用helm install安装 , 具体可以参考:https://github.com/TencentBlueKing/bk-ci/blob/master/docs/install/kubernetes.md

**Comment by ctd1249746051** [comment]
好的谢谢，关闭config-server可以解决这个问题

但是启动assembly会报错indexService冲突的问题，而单独启动project微服务是可以正常启动的，并且下载1.9.15RC1的slim包也会有这种问题，请问是代码本身的问题吗？

assembly报错如下：

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023.10.09 00:16:00,083||| [        main] ERROR o.springframework.boot.SpringApplication 835 Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.tencent.devops.AssemblyApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'indexService' for bean class [com.tencent.devops.log.service.IndexService] conflicts with existing, non-compatible bean definition of same name and class [com.tencent.devops.openapi.service.IndexService]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at com.tencent.devops.common.service.MicroServiceApplication.run(MicroServiceApplication.kt:40)
        at com.tencent.devops.AssemblyApplicationKt.main(AssemblyApplication.kt:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'indexService' for bean class [com.tencent.devops.log.service.IndexService] conflicts with existing, non-compatible bean definition of same name and class [com.tencent.devops.openapi.service.IndexService]
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
        ... 21 common frames omitted

**Comment by ctd1249746051** [comment]
好的谢谢，关闭config-server可以解决这个问题

但是启动assembly会报错indexService冲突的问题，而单独启动project微服务是可以正常启动的，并且下载1.9.15RC1的slim包也会有这种问题，请问是代码本身的问题吗？

assembly报错如下：

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023.10.09 00:16:00,083||| [        main] ERROR o.springframework.boot.SpringApplication 835 Application run failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.tencent.devops.AssemblyApplication]; nested exception is org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'indexService' for bean class [com.tencent.devops.log.service.IndexService] conflicts with existing, non-compatible bean definition of same name and class [com.tencent.devops.openapi.service.IndexService]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:188)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at com.tencent.devops.common.service.MicroServiceApplication.run(MicroServiceApplication.kt:40)
        at com.tencent.devops.AssemblyApplicationKt.main(AssemblyApplication.kt:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'indexService' for bean class [com.tencent.devops.log.service.IndexService] conflicts with existing, non-compatible bean definition of same name and class [com.tencent.devops.openapi.service.IndexService]
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.checkCandidate(ClassPathBeanDefinitionScanner.java:349)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:287)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:295)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:249)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:206)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:174)
        ... 21 common frames omitted

**Comment by stubenhuang** [comment]
是的, 最新版的assembly有类冲突, 是已知问题, 在整理中 , 后续会修复 (但没有那么快🥺)

**Comment by ctd1249746051** [comment]
好的谢谢

**Comment by shichaowei** [comment]
大佬，类冲突有解决吗？

> 是的, 最新版的assembly有类冲突, 是已知问题, 在整理中 , 后续会修复 (但没有那么快🥺)
