### ISSUE TITLE
1.11版本的process启动有循环依赖的问题

### ISSUE THREAD

**Issue by exfeipingli20231012** [TencentBlueKing/bk-ci#9774]
**报错log如下：**

2023.12.06 16:39:29,956||| [        main] INFO  ConditionEvaluationReportLoggingListener 136 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023.12.06 16:39:30,158||| [        main] ERROR o.springframework.boot.SpringApplication 835 Application run failed
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jerseySwaggerConfig' defined in class path resource [com/tencent/devops/common/web/WebAutoConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceScmWebhookResourceImpl' defined in file [C:\Users\chen\IdeaProjects\bk-ci-1.11.0-rc.2\src\backend\ci\core\process\biz-process\build\classes\kotlin\main\com\tencent\devops\process\api\ServiceScmWebhookResourceImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'samplePipelineBuildWebhookService': Requested bean is currently in creation: Is there an unresolvable circular reference?
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
    at org.springframework.boot.SpringApplication.re

**Comment by mingshewhe** [comment]
在启动的时候增加-Dspring.main.allow-circular-references=true
